### ISSUE TITLE
What is this repo about?

### ISSUE THREAD

**Issue by adeluccar** [FionaDong/anki_download_voice_ruby#1]
Hi! I'm a fan of anki. I'm trying to wrap my head around this code but can't understand it. 
What is it for?

**Comment by FionaDong** [comment]
I am a Chinese anki user trying to learn English, I know there is a feature that anki let users to record their voice for particular words, but I think my pronunciation not good enough so I wrote this ruby code to download online pronunciation and save it to local for my reference.  
This little program just visit particular website in Chinese Mainland and download corresponding record automatically. Sorry for the inadequate information for this repo, I could add some explanatory note if you need. Let me know if you need, thank you for your concern.

**Comment by adeluccar** [comment]
Thanks! That explains it quite well. I might even use it myself. How do I use it?

**Comment by FionaDong** [comment]
Well, that quite depends on which website you plan to download from, it download voice and phonetic symbol from http://dict.youdao.com/ for English words&phrases and http://dict.baidu.com for Chinese words.
Since it's only a semi-finished product that I plan to use it myself, it could be tedious to config everything like which website you prefer, where your anki media path is...But I will add some more comments in the code, hope it helps.
Basically, the main program is **engine_anki.rb**
1. config where the **log** file is located.
2. **to_folder** is the anki media path, you could find it under Anki folder itself, quite similar.
3. **deck_file** is a collection of deck id which I extract them from DataBase, here is sqlite3, I made it as a voice download reference for which deck need download, for the other decks just ignore them.
4. initial **db** connection, you could find it under Anki folder itself, quite similar.
5. The most important **resource** program, it quite depends on webpage structure when parsing phonetic symbol and voice, so different webpage different handling. I involved nokogiri for parsing, it must be anything better.
6. The next part is to get every word in DB and call corresponding resource download , such as **resource_bd.download_resource(to_folder)** for baidu.com.
- check if any phonetic symbol or voice inadequate for that word
- download phonetic symbol via webpage parsing and voice via ruby I/O.

If you are interested in webpage parser, you could add your favorite resource program from different website.

**Comment by hydeenicole** [comment]
To have a repow, it can be as soon as two months. banks want there payments and they do ccome sadly and take your car
